services:
  portainer:
    image: portainer/portainer-ce:2.27.9
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"   # Accès HTTPS
      - "9000:9000"   # Accès HTTP
    command: --host unix:///var/run/docker.sock
    user: "0:0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - docker_network

volumes:
  portainer_data:

networks:
  docker_network:
    driver: bridge   # le réseau sera créé automatiquement
